### ISSUE TITLE
Readme is incorrect

### ISSUE THREAD

**Issue by code-vicar** [thenativeweb/boolean#1]
This library is much more permissive than the readme claims.

Take this code as an example

```
var boolean = require('boolean')

console.log(boolean([false]))
console.log(boolean({}))
console.log(boolean(001))
console.log(boolean(100))
console.log(boolean('negative'))
console.log(boolean('hellyo'))
console.log(boolean('noyesno'))
console.log(boolean('321'))
```

All of these expressions will return true

Any object which is truthy and not a string will return true
Any string that contains a substring of 't', 'y', or 'yes' will return true
Any string that begins with the word 'true' or ends with the number 1 will return true

**Comment by goloroden** [comment]
Hi @code-vicar!

First of all, thanks a lot for pointing out these issues, and you are absolutely right - the module is way too permissive :-(

There was a bug in a regular expression in the code, and additionally, there were a few other glitches, too. I now fixed all of them, and added more tests.

Could you please have another look at it (an updated `0.1.1` version is on npm now) whether it now works according to your expectations? Please let me know your results, so that I can either fix more cases, or close this issue.

Thanks :-)

**Comment by code-vicar** [comment]
Works great now,
thanks.

**Comment by goloroden** [comment]
:-)
