### ISSUE TITLE
Lookbehind assertions are not compatible with FF

### ISSUE THREAD

**Issue by sulabhjain** [thenativeweb/boolean#17]
https://github.com/thenativeweb/boolean/blob/329dac41adae790fb2f0474d1c7db610ca1da91d/lib/boolean.ts#L3

Lookbehind assertions got introduced in early 2018 and browsers like FF still don't support it. In order for this library to be more acceptable to work with all the major browsers, I would recommend to use look ahead assertions at this point in time. 

This works on recent versions of Chrome and Safari. I haven't tested on IE.

Ref: https://stackoverflow.com/questions/641407/javascript-negative-lookbehind-equivalent#

**Comment by goloroden** [comment]
Hey @sulabhjain 👋 

Thanks for bringing this issue up!

Generally we're using the approach of only supporting things for the latest Node.js LTS, since this is the platform we build upon. Since we have lots of open-source modules (and this one is not our core product), we try to avoid additional maintenance work, which in this case would happen, if we add special support for Firefox (which, to put it simply, just fails to support an already established standard).

Hence, our suggestion would be that you either use a precompilation step such as Babel if you need this module to work with Firefox, or that you fork this repository, and adjust the code yourself.

Sorry for not having a better answer, but I hope you understand why we decided to go this way.

All the best 😊 

Golo
