### ISSUE TITLE
v3.1.3 dependent on node >= 16.7.0

### ISSUE THREAD

**Issue by timichal** [thenativeweb/boolean#317]
The recent v3.1.3 has a set dependency for node >= 16.7.0. As it's a patch release, this breaks other packages dependent on it without a specified exact version number (in our case, pm2) when using a lower node version.

**Comment by nathanmarcos** [comment]
Same here:
```
error boolean@3.1.3: The engine "node" is incompatible with this module. Expected version ">= 16.7.0". Got "14.17.1"
error Found incompatible module.
```

**Comment by Vladislao** [comment]
A way to find out that there's a separate package for boolean

**Comment by dorin-musteata** [comment]
Same here

**Comment by gvaartjes** [comment]
same here

**Comment by mchumakov** [comment]
same here :)))

**Comment by timneedham** [comment]
same here :wink: :gb:

**Comment by MaksimFedyanin** [comment]
add in package.json:
`"resolutions": { "boolean": "3.1.2" }`

**Comment by goloroden** [comment]
@timichal Thanks for bringing up this issue.

As it seems, two things happened here:

- First, we bumped a dependency which should have caused a patch release, but which failed for whatever reason, and which went unnoticed.
- Second, today we update a dev dependency, and introduced the `engine` field to the `package.json` file.

This second change caused the build to re-run, and so we had a `patch` release, although we did not even want to publish this second change yet.

However… we are currently updating all our modules to prepare for ESM, and this actually requires Node 16+ for a variety of reasons. As we do not test on 16.0, 16.1, 16.2, and so on, we just defined that whenever we touch a module and update it, we are going to update the field to the current version of Node.js, since this is the version against which we develop and test.

I understand that this causes problems downstream. One option is to handle it in the way that was pointed out by @MaksimFedyanin (by the way, thanks for that!).

Is the message you get actually an error in terms of a build-breaker, or is it a warning that is annoying, but can basically be ignored?

**Comment by yarinvak** [comment]
@goloroden this is a deal breaker and cause our build to break even though we don't use `boolean` package directly, but using `snyk` which is a dependent of your package

**Comment by goloroden** [comment]
@yarinvak Thanks for the info, we'll take a look into this, and will think of a solution which works for you as well as for us.

Please give us a little time for this, in the meanwhile please refer to the solution provided by @MaksimFedyanin

**Comment by timichal** [comment]
This is indeed a build breaking change in my case, through a transient dependency of `pm2@5.1.0` (haven’t checked which one, might be `snyk`.

I understand the requirement of node16+ for ESM changes, but as it’s a breaking change, that shouldn’t be a patch version.

**Comment by gvaartjes** [comment]
@goloroden this is a build breaker for the pm2 package

**Comment by goloroden** [comment]
What I don't understand right now is why it's a build-breaker, because according to https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines it should be advisory-only 🤔

**Comment by Vladislao** [comment]
```
yarn global add pm2 --ignore-engines
```

**Comment by timichal** [comment]
@goloroden I suppose it might be a yarn thing

**Comment by goloroden** [comment]
Okay, as it seems this was even reported a as an inconsistency to yarn (see https://github.com/yarnpkg/yarn/issues/6627).

The yarn team closed it because they see it as an advantage over npm – from our point of view this is a discrepancy of how the `package.json` file is meant to work 🙄

However, this won't solve the problem … of course, using `--ignore-engines` is a viable workaround.

We probably are going to remove the `engines` field again …

**Comment by coremyslo** [comment]
@goloroden revert in release 3.1.4 and adding back in 4.0.0 could be an option

**Comment by goloroden** [comment]
Okay, so … we are currently updating our build process (which actually affects this), and then are going to release new versions without the `engines` field.

This will take us a few hours (sorry for that), and once this is done, we'll provide a fixed version of the `boolean` module as well 😊

**Comment by amopportunities** [comment]
ETA?

**Comment by goloroden** [comment]
Due to some unexpected problems, tomorrow 😕

**Comment by Unitech** [comment]
That is ridiculous

**Comment by gfyoung** [comment]
Why not just unpublish `3.1.3` from the registry?

Then you guys will have all the time you need to address the concerns in this issue, while the rest of us can continue working.

I understand that you guys have internal development processes, but leaving all of these packages broken is far from ideal.

**Comment by goloroden** [comment]
Sorry that it took that long, we had a number of problems summing up – however, we now finally have version 3.1.4 on npm, which does not use the `engines` field any more and should now work as before. 🎉

@gfyoung Thanks for your suggestion with unpublishing, unfortunately, the grace period was over, so it was not possible to unpublish any more, otherwise we would have done so. However, thanks for the constructive feedback 😊

To anyone else: Thanks for being nice and constructive and sympathetic 😊

Oh, and one last thing, @Unitech: It makes me sad that your only comment is `That is ridiculous`. You apparently have no problem using other people's code, but you have a huge problem understanding and accepting that sometimes things don't work as expected.

As you maybe can imagine it was not our intention to break this, and we wanted to fix it in the right way, which turned out to use more time than we expected. At my place, it's now 1 minute past midnight, and I have been spending my entire evening on this topic, instead of spending time with my family.

Not providing any constructive help, not sending a pull request, not doing anything helpful, but ONLY complaining and shouting out at people – for code that you did not pay a single cent for – *THAT* is what I call ridiculous. You can't imagine how glad I am that we got rid of `pm2` years ago. Today you have proven that if software is crap, one reason for this is that the people behind it are arrogant and demanding in a selfish way. Good to know whom not to talk to in the future.

To anyone else: As said, thanks for being nice, constructive, and understanding 😊

**Comment by nonara** [comment]
Thanks for the fix!

First, we agree on all of your points about free software and how thankless the job of a maintainer can be. Unfortunately, I know that all too well!

I also agree that Unitech certainly could have been more respectful. 

With that said, as someone whose been in a similar spot, I'd like to share a few thoughts, not in hostility, but in the hope that it may be helpful.

As an OSS maintainer, although it is thankless and tiring, I believe we still do inherit some level responsibility in sharing our work and in having that work used to prop up others' systems. This responsibility does tend to grow proportional to the popularity of the library. Funny enough, this often means tiny 17 LOC libraries end up being the linchpin in massive entities.

I may be misunderstanding, but it sounds like you have a build process which was causing the line to be added to the package, and you were trying to fix the build process so the regular build / publish methodology could be used. 

Ultimately, I think the underlying point Unitech was making was that this approach lacks the sort of expected courtesy of prioritizing the other systems, especially when that seems to be easily attainable.

In this case, the breaking change is a single line in the `package.json` file. Yet, it was breaking massive things for thousands of people. In such a case, the immediate reaction should be to simply clone the repo (outside the greater build system), revert the commit, and publish a new patch. Then you have time to do what you need on your end. And, if something you have somehow relies on the broken version, you can pin your own software to the previous version until I can get it updated. I think this ends up being much more reasonable than expecting thousands of others to do that.

I can imagine the reason for Unitech's frustration, if he is the maintainer of pm2, is that he's going to have hundreds of messages and tickets rolling in. I've also been in that spot, yet with less volume, I imagine.

Anyway, just a few thoughts that I hope can be helpful. 

I also wanted commend you on your informative updates along the way and for the willingness to put the time in to get it fixed! Thanks, and take care!

**Comment by rarkins** [comment]
@goloroden thanks for spending the time to fix it as fast as you could

**Comment by pmarrone** [comment]
@goloroden Thank you for the quick fix. It is really appreciated.
