### ISSUE TITLE
Feature Request: isBooleanable()

### ISSUE THREAD

**Issue by darkpixel** [thenativeweb/boolean#340]
I would love to see a function that tells you if an object/string/whatever is one of the "booleanable" options.

For example isBooleanable() would return True for the values you consider a truth or false: true, false, 'Y', 'N', '1', 0, 'on', 'off', etc...

But when passing something that isn't one of the covered true/false items, it would return False: 'computer', '2022-02-15T11:37:00-08:00', etc...

That would allow you to check if an object is something that should evaluate to a true/false before calling boolean() and potentially getting False as the default result.

**Comment by goloroden** [comment]
Thanks for bringing up this issue.

Actually, this would introduce some new kind of semantics. Right now we only have values that are seen as equivalent to `true`, anything that is not one of these values is implicitly considered to be `false`. So we don't make a distinction between `off`, `no`, and similar thanks on the one and things such as `computer`, a date, and so on, on the other hand.

However, it would make sense to have the opposite values defined as well, so that e.g. `off` is equivalent to `false`. Anyway, if we keep the existing code as it is, this leads to inconsistent results:

```javascript
console.log(isBooleanable('T')); // => true
console.log(boolean('T')); // => true

console.log(isBooleanable('F')); // => true
console.log(boolean('F')); // => false

console.log(isBooleanable('nonsense')); // => false
console.log(boolean('nonsense')); // => false
```

So we now have two different kinds of values that both evaluate to `false`. This seems to be wrong, so in the last case `boolean` should not return `false`, but something else (what? `undefined`? `null`? Throw an exception? …?). And this is a pretty heavy breaking change.

So I'm not sure on this, TBH. What do you think on this?

**Comment by darkpixel** [comment]
I don't see a problem with leaving ```boolean('nonsense');``` as it is returning ```false```.

That wouldn't break existing code, and it would be up to the developer to decide if they want to call ```isBooleanable()``` on their own.

In my particular use-case, I'm dealing with an absolutely horrible database that is full of character fields with a length of 1 (Y/N/T/F), small integer fields (0/1), and actual bit fields (0/1).  They should have been Boolean fields, but it's a legacy DB from ~1993 and the developers were already brain-damaged to begin with. ;)

I am syncing the database to an API, so I would do something like this pseudo-code:
```
if (isBooleanable(row[field_name])) {
  api_call({ field_name: boolean(row[field_name]) });
} else {
  // There's actually other logic here to deal with datetime and time fields with no timezone/offset info
  api_call({ field_name: row[field_name] });
}
```

**Comment by goloroden** [comment]
Makes sense, thanks for sharing your thoughts 😊

**Comment by darkpixel** [comment]
Whoa.  That was quick.  I'll stary play testing soon. :)
