### ISSUE TITLE
Browser-ready version?

### ISSUE THREAD

**Issue by niftylettuce** [thenativeweb/boolean#6]
Would be nice!

**Comment by niftylettuce** [comment]
Yeah, one that would make standalone `window.boolean` available or something.

**Comment by niftylettuce** [comment]
Here's how I make my standalone builds btw with browserify https://github.com/cabinjs/cabin/blob/master/package.json#L152-L153

**Comment by goloroden** [comment]
Thanks for the link!

Actually, we explicitly decided against providing special browser builds. The reason for this is as follows:

We have a unified build pipeline for all our modules, and we want to keep it that way. This means that we either have to provide browser builds for everything or for nothing. We don't want to introduce special build steps for individual repos, as this leaves you individual builds per repo.

Since we assume that most JavaScript developers use a bundler such as webpack or browserify anyway, this would mean adding a feature (that needs to be maintained, documented, …) for a way of developing we don't want to use (and that we believe only a low number of other people uses).

Actually, the demand for special browser builds seems to be pretty low, given that we have almost 100 modules on npm, but are rarely asked for this. And, last but not least: Whoever is in the need of such a build can easily create it on their own by using the given code as the foundation.

So, to cut a long story short: While technically doable, we won't implement this. I hope that this is okay for you. I'm sorry if this causes additional work at yours, but from our point of view, as outlined, it's not worth the effort.

**Comment by niftylettuce** [comment]
np understood
